"""Add pie chart cells to the 03_explore_vietnam_dataset.ipynb notebook."""
import json
import os

notebook_path = os.path.join(
    os.path.dirname(__file__),
    "03_explore_vietnam_dataset.ipynb"
)

with open(notebook_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# --- Markdown cell ---
md_cell = {
    "cell_type": "markdown",
    "id": "pie_chart_header",
    "metadata": {},
    "source": [
        "### 3. Phân bố ảnh theo Đường (Street) và theo Split (Train/Valid/Test)\n",
        "Biểu đồ tròn thể hiện trong 500 tấm ảnh thuộc tập `VietNamDataset`, mỗi ảnh thuộc đường nào và nằm trong folder đầu vào nào.\n",
        "\n",
        "**Nguyên lý mapping:** Dựa vào Base ID (phần số trước `_jpg`) của ảnh trong train/valid/test, ta khớp ngược lại với các folder gốc (DinhCongTrangStreet, HoangHuuNamStreet, ...) để xác định nguồn gốc."
    ]
}

# --- Code cell: Pie chart ---
code_cell = {
    "cell_type": "code",
    "execution_count": None,
    "id": "pie_chart_code",
    "metadata": {},
    "outputs": [],
    "source": [
        "# ========================================================\n",
        "# Biểu đồ tròn: Phân bố 500 ảnh theo Đường và theo Split\n",
        "# ========================================================\n",
        "import os\n",
        "import glob\n",
        "import matplotlib.pyplot as plt\n",
        "import numpy as np\n",
        "\n",
        "DATASET_PATH = \"../data/VietNamDataset\"\n",
        "\n",
        "def extract_base_id(filename):\n",
        "    \"\"\"Trích xuất ID gốc (bỏ hậu tố Roboflow)\"\"\"\n",
        "    basename = os.path.splitext(os.path.basename(filename))[0]\n",
        "    if \"_jpg\" in basename:\n",
        "        return basename.split(\"_jpg\")[0]\n",
        "    return basename\n",
        "\n",
        "# 1. Thu thập tên ảnh từ các folder gốc (đường/street)\n",
        "EXCLUDE = {'train', 'valid', 'test', 'full_dataset'}\n",
        "source_map = {}  # base_id -> street_folder_name\n",
        "street_folders = []\n",
        "\n",
        "for item in sorted(os.listdir(DATASET_PATH)):\n",
        "    full = os.path.join(DATASET_PATH, item)\n",
        "    if os.path.isdir(full) and item not in EXCLUDE:\n",
        "        street_folders.append(item)\n",
        "        for f in os.listdir(full):\n",
        "            if f.lower().endswith(('.jpg', '.png', '.jpeg')):\n",
        "                base_id = os.path.splitext(f)[0]\n",
        "                source_map[base_id] = item\n",
        "\n",
        "# 2. Mapping từng ảnh trong train/valid/test -> đường gốc\n",
        "per_split = {}  # split -> {street: count}\n",
        "overall = {}    # street -> total_count\n",
        "\n",
        "for split in ['train', 'valid', 'test']:\n",
        "    img_path = os.path.join(DATASET_PATH, split, 'images')\n",
        "    if not os.path.exists(img_path):\n",
        "        continue\n",
        "    per_split[split] = {}\n",
        "    for f in os.listdir(img_path):\n",
        "        if not f.lower().endswith(('.jpg', '.png', '.jpeg')):\n",
        "            continue\n",
        "        base_id = extract_base_id(f)\n",
        "        folder = source_map.get(base_id, 'Không xác định')\n",
        "        per_split[split][folder] = per_split[split].get(folder, 0) + 1\n",
        "        overall[folder] = overall.get(folder, 0) + 1\n",
        "\n",
        "total = sum(overall.values())\n",
        "print(f\"Tổng số ảnh trong train/valid/test: {total}\")\n",
        "print(f\"Số folder gốc (đường): {len(street_folders)}\")\n",
        "print(f\"\\n{'Đường (Street Folder)':<55} {'Số lượng':>8} {'Tỷ lệ':>8}\")\n",
        "print('-' * 75)\n",
        "for folder in sorted(overall.keys()):\n",
        "    count = overall[folder]\n",
        "    pct = count / total * 100\n",
        "    print(f\"{folder:<55} {count:>8} {pct:>7.1f}%\")\n",
        "\n",
        "# ===========================\n",
        "# BIỂU ĐỒ TRÒN TỔNG THỂ\n",
        "# ===========================\n",
        "\n",
        "# Rút gọn tên đường cho biểu đồ\n",
        "SHORT_NAMES = {\n",
        "    'DinhCongTrangStreet': 'Đinh Công Tráng',\n",
        "    'HoangHuuNamStreet': 'Hoàng Hữu Nam',\n",
        "    'Inter-hamlet_Roads_Alleys_(Rural_Features)': 'Đường liên xóm',\n",
        "    'National_Highway_1': 'Quốc lộ 1',\n",
        "    'Provincial_Road_867': 'Tỉnh lộ 867',\n",
        "    'Provincial_Road_867(1)': 'Tỉnh lộ 867(1)',\n",
        "    'Pham_Van_Bach_Street_(Urban_Intersections) - X': 'Phạm Văn Bạch',\n",
        "    'RRural_Road -X': 'Đường nông thôn (X)',\n",
        "    'Rural_Road': 'Đường nông thôn',\n",
        "    'Rural_Road_(CuuLongRiver) - X': 'Đường Cửu Long',\n",
        "    'Không xác định': 'Không xác định',\n",
        "}\n",
        "\n",
        "labels_overall = []\n",
        "sizes_overall = []\n",
        "for folder in sorted(overall.keys()):\n",
        "    short = SHORT_NAMES.get(folder, folder)\n",
        "    labels_overall.append(f\"{short}\\n({overall[folder]})\")\n",
        "    sizes_overall.append(overall[folder])\n",
        "\n",
        "colors = plt.cm.Set3(np.linspace(0, 1, len(labels_overall)))\n",
        "\n",
        "fig, axes = plt.subplots(1, 2, figsize=(20, 8))\n",
        "\n",
        "# -- Pie chart tổng thể --\n",
        "wedges, texts, autotexts = axes[0].pie(\n",
        "    sizes_overall, labels=labels_overall, autopct='%1.1f%%',\n",
        "    colors=colors, startangle=140, pctdistance=0.8,\n",
        "    wedgeprops={'linewidth': 1.5, 'edgecolor': 'white'},\n",
        "    textprops={'fontsize': 8}\n",
        ")\n",
        "for t in autotexts:\n",
        "    t.set_fontsize(7)\n",
        "    t.set_fontweight('bold')\n",
        "axes[0].set_title(\n",
        "    f'Phân bố {total} ảnh theo Đường (tổng thể)',\n",
        "    fontsize=14, fontweight='bold', pad=20\n",
        ")\n",
        "\n",
        "# -- Stacked bar chart theo split --\n",
        "split_names = ['train', 'valid', 'test']\n",
        "unique_folders = sorted(overall.keys())\n",
        "x = np.arange(len(split_names))\n",
        "bottom = np.zeros(len(split_names))\n",
        "bar_colors = plt.cm.Set3(np.linspace(0, 1, len(unique_folders)))\n",
        "\n",
        "for idx, folder in enumerate(unique_folders):\n",
        "    vals = [per_split.get(s, {}).get(folder, 0) for s in split_names]\n",
        "    short = SHORT_NAMES.get(folder, folder)\n",
        "    axes[1].bar(x, vals, bottom=bottom, label=short,\n",
        "                color=bar_colors[idx], edgecolor='white', linewidth=0.5)\n",
        "    bottom += vals\n",
        "\n",
        "axes[1].set_xticks(x)\n",
        "axes[1].set_xticklabels([f'{s}\\n({sum(per_split.get(s, {}).values())})' for s in split_names],\n",
        "                         fontsize=11)\n",
        "axes[1].set_ylabel('Số lượng ảnh', fontsize=11)\n",
        "axes[1].set_title('Phân bố theo Split và Đường', fontsize=14, fontweight='bold')\n",
        "axes[1].legend(loc='upper right', fontsize=7, ncol=2,\n",
        "               title='Đường', title_fontsize=9)\n",
        "\n",
        "# Thêm số liệu lên bar\n",
        "for i, s in enumerate(split_names):\n",
        "    total_split = sum(per_split.get(s, {}).values())\n",
        "    axes[1].text(i, total_split + 2, str(total_split),\n",
        "                ha='center', fontweight='bold', fontsize=10)\n",
        "\n",
        "plt.tight_layout()\n",
        "plt.savefig('eda_outputs/pie_chart_street_distribution.png', dpi=150, bbox_inches='tight')\n",
        "plt.show()\n",
        "print(\"\\n✅ Đã lưu biểu đồ vào: eda_outputs/pie_chart_street_distribution.png\")"
    ]
}

# Append cells
nb["cells"].append(md_cell)
nb["cells"].append(code_cell)

with open(notebook_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, ensure_ascii=False, indent=1)

print("✅ Đã thêm 2 cells (markdown + code) vào cuối notebook 03_explore_vietnam_dataset.ipynb")
